image: gitpod/workspace-node

tasks:
    - before: ${GITPOD_REPO_ROOT}/init.sh
      command: echo 'some task'
    - before: atop -e 00:01
      command: echo 'some task'
    # - init: ${GITPOD_REPO_ROOT}/init.sh
    #   command: echo 'some task'